repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        exclude: ^dist/
        language_version: python3.9