version = 0.1
["sam-env-dev.toml"]
["sam-env-dev.toml".deploy]
["sam-env-dev.toml".deploy.parameters]
stack_name = "authorizer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15l3l7jbrfnmw"
s3_prefix = "authorizer"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentType=\"Dev\""
image_repositories = []
