AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mqtt_custom_auth

  Sample SAM Template for mqtt_custom_auth

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  UnsignedAuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: iot.amazonaws.com
      SourceArn: !GetAtt  UnsignedAuthorizer.Arn
      FunctionName: !GetAtt AuthFunction.Arn

  AuthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/authorizer
      Handler: authorizer.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_ACCOUNT_ID: !Sub ${AWS::AccountId}
          DYNAMO_TABLE_NAME: !Ref Table
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "dynamodb:Get*"
                - "dynamodb:Query"
              Resource: !GetAtt Table.Arn
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: "Client_ID"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: "Client_ID"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "MQTTAuthTable"

  UnsignedAuthorizer:
    Type: AWS::IoT::Authorizer
    Properties:
      AuthorizerFunctionArn: !GetAtt AuthFunction.Arn
      AuthorizerName: "MqttAuth-Unsigned"
      EnableCachingForHttp: true
      SigningDisabled: True
      Status: "ACTIVE"

Outputs:
  UnsignedAuthorizerName:
    Description: "Name of unsigned authorizer"
    Value: !Ref UnsignedAuthorizer

  UnsignedAuthorizerStatus:
    Description: "Unsigned authorizer active"
    Value: true

  TableName:
    Description: "Table name"
    Value: !Ref Table
